apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-fs-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data"
