apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms2048m -Xmx2048m
        - name: cluster.initial_master_nodes
          value: es01
        - name: node.name
          value: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        imagePullPolicy: ""
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
          - mountPath: /data
            name: elasticsearch-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: elasticsearch-claim1
          persistentVolumeClaim:
            claimName: elasticsearch-claim1 
status: {}
